# Generated by Django 4.1.7 on 2023-06-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='choices',
            field=models.CharField(choices=[('p', 'play'), ('r', 'Read'), ('w', 'Walk')], default=('p', 'play'), max_length=1),
        ),
    ]
